version: "2"
linters:
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - exhaustive
    - exhaustruct
    - forbidigo
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
formatters:
  enable:
    - goimports
